In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days


In [52]:
X = linspace(0., 5., 6)
Theta = array([1,2, 0,0, 0])

In [55]:
powers = array(range(Theta.size)).reshape(-1,1)
X_powers = (X**powers).T
X_powers, X_powers.shape

(array([[   1.,    0.,    0.,    0.,    0.],
        [   1.,    1.,    1.,    1.,    1.],
        [   1.,    2.,    4.,    8.,   16.],
        [   1.,    3.,    9.,   27.,   81.],
        [   1.,    4.,   16.,   64.,  256.],
        [   1.,    5.,   25.,  125.,  625.]]), (6, 5))

In [49]:
Y = X_powers.dot(Theta)

ValueError: shapes (3,10) and (5,) not aligned: 10 (dim 1) != 5 (dim 0)

In [44]:
X, X_powers, Y

(array([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]]),
 array([[   1.,    1.,    0.,    3.,    0.,    9.,    0.,   27.],
        [   1.,    1.,    1.,    4.,    1.,   16.,    1.,   64.],
        [   1.,    1.,    2.,    5.,    4.,   25.,    8.,  125.]]),
 array([  1. ,   3.5,   6. ,   8.5,  11. ]))

In [40]:
range(3)

[0, 1, 2]