In [1]:
%pylab inline

Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 28 days
Vendor:  Continuum Analytics, Inc.


Populating the interactive namespace from numpy and matplotlib


Package: mkl
Message: trial mode expires in 28 days


In [62]:
num_samples = 6
num_classes = 3
A = floor(rand(num_samples) * num_classes)
B = array([[1 if A[i] == k else 0 for k in range(num_classes)] for i in range(num_samples)])
make_

In [63]:
A, B

(array([ 0.,  0.,  2.,  2.,  1.,  1.]), array([[1, 0, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0]]))

In [47]:
B.shape[1]

2

In [61]:
D = rand(6,3) *10
array([exp(x)/exp(x).sum() for x in D]).sum(1)

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [64]:
def norm(x):
    e = exp(x)
    return e/e.sum()
array([norm(x) for x in D])

array([[  3.02893033e-02,   9.69343037e-01,   3.67659291e-04],
       [  2.75559599e-02,   2.48079277e-02,   9.47636112e-01],
       [  3.29589964e-01,   6.58353136e-01,   1.20568991e-02],
       [  8.59875226e-01,   1.04997298e-01,   3.51274754e-02],
       [  6.93307470e-02,   9.28488251e-01,   2.18100237e-03],
       [  5.21715468e-02,   3.72877052e-01,   5.74951401e-01]])

In [77]:
def make_row(x):
    a = zeros(num_classes)
    a[x] = 1.
    return a
array([make_row(x) for x in A])

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.]])

In [78]:
zeros_like(B)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])