In [1]:
%pylab inline

Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 28 days
Vendor:  Continuum Analytics, Inc.


Populating the interactive namespace from numpy and matplotlib


Package: mkl
Message: trial mode expires in 28 days


In [45]:
num_samples = 6
num_classes = 2
A = floor(rand(num_samples) * 2)
B = array([[1 if A[i] == k else 0 for k in range(num_classes)] for i in range(num_samples)])

In [46]:
A, B

(array([ 0.,  1.,  1.,  0.,  1.,  1.]), array([[1, 0],
        [0, 1],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1]]))

In [47]:
B.shape[1]

2

In [53]:
D = rand(6,3) *10
[exp(x)/exp(x).sum() for x in D]

[array([ 0.0060144 ,  0.01000221,  0.98398339]),
 array([ 0.97807493,  0.02015004,  0.00177503]),
 array([ 0.01756228,  0.98123775,  0.00119997]),
 array([ 0.98357444,  0.00262946,  0.0137961 ]),
 array([  1.99465799e-03,   2.88670295e-04,   9.97716672e-01]),
 array([ 0.00359176,  0.75812987,  0.23827837])]

In [55]:
def norm(x):
    e = exp(x)
    return e/e.sum()
[norm(x) for x in D]

[array([ 0.0060144 ,  0.01000221,  0.98398339]),
 array([ 0.97807493,  0.02015004,  0.00177503]),
 array([ 0.01756228,  0.98123775,  0.00119997]),
 array([ 0.98357444,  0.00262946,  0.0137961 ]),
 array([  1.99465799e-03,   2.88670295e-04,   9.97716672e-01]),
 array([ 0.00359176,  0.75812987,  0.23827837])]

In [58]:
array([2,3]) * array([1./2., 1./3.])

array([ 1.,  1.])