Configuring the environment
=======================

Python Distributions
-------------------

Numerical and scientific packages for Python are not part of the core library and sometimes are missing. Moreover, for optimal performance they should be linked against fast mathematical libraries. We recommend using a prebuilt scientific Python distribution:

- Windows:
	- WinPython https://winpython.github.io/ Free, new packages can be installed from http://www.lfd.uci.edu/~gohlke/pythonlibs/
- Windows, Linux, Mac:
	- Anaconda Python https://store.continuum.io/cshop/anaconda/ free for academic usage, you will need to obtain a license though
	- Enthought Canopy https://www.enthought.com/products/canopy/

On computers in **lab 110 and 137** I have installed Anaconda Python, to use it please `source /pio/os/anaconda/set-env.sh` in your bash prompt.

Text editor
-------------

I like using Eclipse and [Pydev](http://pydev.org/). Subjectively, it has the best code completion and remote debugging capabilities.

Other environments are:

- any other Python GUI (PyCharm, ...)
- Spyder - something Matlab-like, seems promising
- Canopy Editor - comes with Canopy Python, not installed in our labs

Interactive environment
---------------------------------

The best interactive environment is the IPython console. For Windows you will need a decent terminal emulator - such as [ConEmu](https://code.google.com/p/conemu-maximus5/)). IPython also has a web interface, availabla as `ipython notebook`.

I will upload my IPython profile - it has the ability to print the shape of numpy arrays, which is handy for debugging.

## Short IPython description

IPython (Interactive Python) is a better command prompt for Python. Cool features are:

- tab completion
- help - to access type `command?` or `command??`
- magic functions (`%magic`)
- integration with GUI loops, (`%gui`)

Moreover the notebook provides:
- mixing of code and descriptions
- plot embedding
- data pretty-printing

In the notebook we can run cells with `Ctrl+Enter`, while hittin `Shift+Enter` will evaluate a cell and move onto the next one.

3

In [3]:
# Help. This works alsi in the console IPython
help?

In [4]:
help??

In [5]:
# IPython help
?

In [ ]:
%quickref

In [6]:
# Help on magic functions
%magic

In [ ]:
# ! this runs a shell command
!ipython locate profile

## numpy

`numpy` provides a flexible array type, that we will extensively use.

In [7]:
# %pylab loads numerical libraries and adds GUI loop integration.
# Inline means displaying plots in the notebook itself.
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [10]:
tab = [123, 'asdfa', "asfsd", 1.9]
tab.append(5)
tab

[123, 'asdfa', 'asfsd', 1.9, 5]

In [11]:
# Matrices and vectors are created from (nested) lists. Unfortunately there is no shortcut

# now we create a vector
v = array([1,2,3,4])
v

Shape: (4L,)
[1 2 3 4]

In [12]:
# transform a nested array into a matrix
M = array([[1,2],[3,4]])
M3D = array([[[1],[2]],[[3],[4]]])

print M, M3D

Shape: (2L, 2L)
[[1 2]
 [3 4]] Shape: (2L, 2L, 1L)
[[[1]
  [2]]

 [[3]
  [4]]]


In [13]:
# Beware - this will create you a vector (1D array) of lists!
vl = array([[1,2],[3,]])
type(vl[0])

list

In [14]:
# Everything in numpy is a ndarray
type(v), type(M), type(vl)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# ndarray's properties 
x = arange(10).reshape(2,5)
for prop in ['shape','size','dtype','strides','itemsize','nbytes','ndim', 'data']:
    print 'x.%s = %s' % (prop, getattr(x,prop))

x.shape = (2L, 5L)
x.size = 10
x.dtype = int32
x.strides = (20L, 4L)
x.itemsize = 4
x.nbytes = 40
x.ndim = 2
x.data = 	


In [16]:
# ndarray contains elements of only one type

vl[0] = 'lala' # thos works, as v1 contains objects (pointers)
print vl

try:
    v[0] = 'lala' # thsi breaks, because v contains integers
    print v
except:
    print "it failed :("

Shape: (2L,)
['lala' [3]]
it failed :(


In [17]:
# the array constructor takes the dtype argument which forces a certain data type
M = array([[1, 2], [3, 4]], dtype=complex)

M

Shape: (2L, 2L)
[[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]

In [18]:
# create a range as an array
arange(0, 10, 1, dtype='float32') # arguments: start, stop, step

Shape: (10L,)
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]

In [19]:
arange(-1, 1, 0.1)

Shape: (20L,)
[ -1.00000000e+00  -9.00000000e-01  -8.00000000e-01  -7.00000000e-01
  -6.00000000e-01  -5.00000000e-01  -4.00000000e-01  -3.00000000e-01
  -2.00000000e-01  -1.00000000e-01  -2.22044605e-16   1.00000000e-01
   2.00000000e-01   3.00000000e-01   4.00000000e-01   5.00000000e-01
   6.00000000e-01   7.00000000e-01   8.00000000e-01   9.00000000e-01]

In [20]:
linspace(0, 10, 25)

Shape: (25L,)
[  0.           0.41666667   0.83333333   1.25         1.66666667
   2.08333333   2.5          2.91666667   3.33333333   3.75         4.16666667
   4.58333333   5.           5.41666667   5.83333333   6.25         6.66666667
   7.08333333   7.5          7.91666667   8.33333333   8.75         9.16666667
   9.58333333  10.        ]

In [24]:
x= logspace(0, 10, 10, base=2)
y= 2**linspace(0,10,10)

y2 = []
for i in linspace(0,10,10):
    y2.append(2**i)

print 'x', x
print 
print 'y', y

print 
print 'y2', y2


np.all(x==y)

x Shape: (10L,)
[  1.00000000e+00   2.16011948e+00   4.66611616e+00   1.00793684e+01
   2.17726400e+01   4.70315038e+01   1.01593667e+02   2.19454460e+02
   4.74047853e+02   1.02400000e+03]

y Shape: (10L,)
[  1.00000000e+00   2.16011948e+00   4.66611616e+00   1.00793684e+01
   2.17726400e+01   4.70315038e+01   1.01593667e+02   2.19454460e+02
   4.74047853e+02   1.02400000e+03]

y2 [1.0, 2.1601194777846122, 4.666116158304467, 10.079368399158986, 21.772640002790034, 47.031503752819155, 101.59366732596479, 219.45445961038678, 474.04785269109283, 1024.0]


True

In [25]:
# like meshgrid in Matlab - please note that we index the mgrid object instead of 
# calling a function
x, y = mgrid[0:5, 0:5]

In [26]:
x

Shape: (5L, 5L)
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]

In [27]:
y

Shape: (5L, 5L)
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

In [28]:
x, y = ogrid[0:5, 0:5] #we again use array indexing

In [29]:
x

Shape: (5L, 1L)
[[0]
 [1]
 [2]
 [3]
 [4]]

In [30]:
y

Shape: (1L, 5L)
[[0 1 2 3 4]]

In [31]:
zeros((3,3)) #attention - the shape is a tuple

Shape: (3L, 3L)
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

In [37]:
(3, )

(3,)

In [39]:
zeros((3,)) # (3,) makes a 1-element tuple

Shape: (3L,)
[ 0.  0.  0.]

In [40]:
ones((3,3))

Shape: (3L, 3L)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]

In [43]:
random.rand(5,5) # unlike other numpy functions, rand doesn't expect the shape to be a tuple

Shape: (5L, 5L)
[[ 0.76111965  0.93964285  0.41933041  0.55842945  0.62439264]
 [ 0.44874061  0.46456252  0.33545417  0.60848199  0.34596632]
 [ 0.90762389  0.44706821  0.1823977   0.11585945  0.34800039]
 [ 0.66802573  0.78759711  0.29645809  0.30924538  0.69124459]
 [ 0.16682611  0.50653003  0.74490317  0.23950492  0.1567214 ]]

In [44]:
#Indexing:
print v
print v[1]
print v[-1]
print v[:1]
print v[::2]
print v[1::2]
print v[::-1]

Shape: (4L,)
[1 2 3 4]
2
4
Shape: (1L,)
[1]
Shape: (2L,)
[1 3]
Shape: (2L,)
[2 4]
Shape: (4L,)
[4 3 2 1]


In [45]:
M = arange(4).reshape(2,2)
print M
print M[0,0]
print M[-1,-1]
print M[:1,:1]
print M[::2,:]
print M[:,1::2]


Shape: (2L, 2L)
[[0 1]
 [2 3]]
0
3
Shape: (1L, 1L)
[[0]]
Shape: (1L, 2L)
[[0 1]]
Shape: (2L, 1L)
[[1]
 [3]]


In [46]:
print M[0]
print M[0,:]
print M[0, ...]

Shape: (2L,)
[0 1]
Shape: (2L,)
[0 1]
Shape: (2L,)
[0 1]


In [50]:
A = arange(5) + (arange(5)*10.0)[:, newaxis]
A

Shape: (5L, 5L)
[[  0.   1.   2.   3.   4.]
 [ 10.  11.  12.  13.  14.]
 [ 20.  21.  22.  23.  24.]
 [ 30.  31.  32.  33.  34.]
 [ 40.  41.  42.  43.  44.]]

In [55]:
A[::2, ::2]

Shape: (3L, 3L)
[[  0.   2.   4.]
 [ 20.  22.  24.]
 [ 40.  42.  44.]]

In [56]:
# Fancy indexing

A[[0,2,1]] #By default, we take all of the unspecified dimensions

Shape: (3L, 5L)
[[  0.   1.   2.   3.   4.]
 [ 20.  21.  22.  23.  24.]
 [ 10.  11.  12.  13.  14.]]

In [57]:
A[[0,2,1],[0,0,1]] # take the elements on the intersection

Shape: (3L,)
[  0.  20.  11.]

In [58]:
A[ix_([0,2,1],[0,-1])] # take 3 rows and 2 columns

Shape: (3L, 2L)
[[  0.   4.]
 [ 20.  24.]
 [ 10.  14.]]

In [59]:
A[...,0] #ellipsis (...) means to take everything over the unspecified dimensions

Shape: (5L,)
[  0.  10.  20.  30.  40.]

In [60]:
A[:,newaxis,:] #newaxis adds a new unitary dimension

Shape: (5L, 1L, 5L)
[[[  0.   1.   2.   3.   4.]]

 [[ 10.  11.  12.  13.  14.]]

 [[ 20.  21.  22.  23.  24.]]

 [[ 30.  31.  32.  33.  34.]]

 [[ 40.  41.  42.  43.  44.]]]

In [61]:
A[A%2==0] #logical index - takes elements for which the index is True

Shape: (15L,)
[  0.   2.   4.  10.  12.  14.  20.  22.  24.  30.  32.  34.  40.  42.  44.]

In [ ]:
where?

In [62]:
# where and nonzero return indices of nonzero elements. Here we get 2 lists:
# rows and columns of elements less than 4
print where(A<4) 
print nonzero(A%2==0)

(Shape: (4L,)
[0 0 0 0], Shape: (4L,)
[0 1 2 3])
(Shape: (15L,)
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4], Shape: (15L,)
[0 2 4 0 2 4 0 2 4 0 2 4 0 2 4])


In [63]:
# take is akin to fancy indexing, but is a lot faster
print take(A, [0,1], axis=1)
print A[:,[0,1]]

Shape: (5L, 2L)
[[  0.   1.]
 [ 10.  11.]
 [ 20.  21.]
 [ 30.  31.]
 [ 40.  41.]]
Shape: (5L, 2L)
[[  0.   1.]
 [ 10.  11.]
 [ 20.  21.]
 [ 30.  31.]
 [ 40.  41.]]


In [64]:
%timeit take(A, [0,1], axis=1)

The slowest run took 19.92 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 2.45 µs per loop


In [65]:
%timeit A[:,[0,1]]

The slowest run took 16.49 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 5.45 µs per loop


In [66]:
# choose takes an element from many matrices
A0 = zeros((2,3))
A1 = zeros((2,3))+10
A2 = zeros((2,3))+20

choice = randint(0,3,(2,3))
print choice 
print choose(choice,[A0,A1,A2])

Shape: (2L, 3L)
[[1 1 1]
 [0 0 2]]
Shape: (2L, 3L)
[[ 10.  10.  10.]
 [  0.   0.  20.]]


## The anatomy od a ndarray

ndarray is a multidimensional table (matrix or tensor) that holds elements of a single type. It is composed of:

- data: a memory block
- information about elements it holds: `dtype` (data type)
- shape information: shape and strides (offset in bytes along each axis)


In [67]:
A = np.arange(12).reshape(3,4)
A

Shape: (3L, 4L)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [68]:
A.dtype, A.itemsize

(dtype('int32'), 4)

In [69]:
A.ndim, A.shape, A.strides

(2, (3L, 4L), (16L, 4L))

There are two conventions of laying out data in memory:

- Fortran (col-major): elements are put into collumns (when iterating, the index on the left changes fastest)
- C (row-major): elemets are put into rows, the right-most index changest fastest


In [70]:
A.strides

(16L, 4L)

In [71]:
A.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [75]:
# transpose makes the matrix col-major:
AT = A.T
AT.shape, AT.strides

((4L, 3L), (4L, 16L))

In [76]:
AT.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [77]:
A

Shape: (3L, 4L)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [78]:
# this returns a view with different strides
AS = A[::2,::2]
print AS
print AS.shape, AS.strides

Shape: (2L, 2L)
[[ 0  2]
 [ 8 10]]
(2L, 2L) (32L, 8L)


In [79]:
# it also works for transpositions
ATS = A.T[::2,::2]
print ATS
print ATS.shape, ATS.strides

Shape: (2L, 2L)
[[ 0  8]
 [ 2 10]]
(2L, 2L) (8L, 32L)


In [80]:
# Numpy returns views whenever it can - all matrices below share storage!
print A
print AT
print AS
print ATS

Shape: (3L, 4L)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (4L, 3L)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Shape: (2L, 2L)
[[ 0  2]
 [ 8 10]]
Shape: (2L, 2L)
[[ 0  8]
 [ 2 10]]


In [81]:
#Attention - this will change all matrices!
A[0,0]=100
print A
print AT
print AS
print ATS

Shape: (3L, 4L)
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
Shape: (4L, 3L)
[[100   4   8]
 [  1   5   9]
 [  2   6  10]
 [  3   7  11]]
Shape: (2L, 2L)
[[100   2]
 [  8  10]]
Shape: (2L, 2L)
[[100   8]
 [  2  10]]


In [82]:
#Fancy indexing makes copies!
A2 = A[ix_([1,2],[1,2])]
A2[0,0]=1000
print A, A2

Shape: (3L, 4L)
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]] Shape: (2L, 2L)
[[1000    6]
 [   9   10]]


In [ ]:
# Quick question! We have a vector:
V = arange(12)
# We want to build a matrix:
# [[V[0], V[1], V[2]], [V[1], V[2], V[3]], ..., [V[9], V[10], V[11]]

VV = numpy.lib.stride_tricks.as_strided(V, shape=(10,3), strides=array((1,1))*V.itemsize)
VV

In [ ]:
#Warning: as_strided makes no sanity-checks:
numpy.lib.stride_tricks.as_strided(V, shape=(12,3), strides=array((1,1))*V.itemsize)

In [ ]:
#Attention, elements of VV may overlap!
VV[2,2]=1000

print VV
print V

In [ ]:
#Strides allows all sorts of virtual data replication:
numpy.lib.stride_tricks.as_strided(V, shape=(12,3), strides=array((1,0))*V.itemsize)

#Broadcasting

Numpy can operate on matrices of different shapes, as long as they are compatible. The algorithm is as follows:

1. If the operands have a different number of dimensions, pad the shape with 1 *from the left*
2. Match the shapes from the right. There is a match if:
    - the shapes are identical
    - one of the shapes is 1 on None (then the array will be replicated along that dimension)

    NB: this is implemented by adding a dimension with stride 0!

In [83]:
arange(5)[:,None] * arange(5) #[None,:] #Optional, the shape will padded with ones

Shape: (5L, 5L)
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]

In [84]:
# interator over the array in flattened C-order
list(A.flat)

[100, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

References:

- https://github.com/jrjohansson/scientific-python-lectures
- Travis Oliphant, "A guide to numpy" http://csc.ucdavis.edu/~chaos/courses/nlp/Software/NumPyBook.pdf
- scipy lecture notes https://github.com/scipy-lectures/scipy-lecture-notes
